package IU.Forms;

import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 * @author dgc06
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public void cargarTexto(String titulo, String cuerpo){
        tituloJlabel.setText(titulo);
        cuerpoJLabel.setText(cuerpo);
    }
    public Loading(String titulo , String cuerpo) {
       
        initComponents();
        cargarImagenes();
        cargarTexto(titulo, cuerpo);
        this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        cuerpoJLabel = new javax.swing.JLabel();
        tituloJlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\dgc06\\Documents\\Proyectos Java Netbeans\\procesadorXML\\images\\mano.png")); // NOI18N

        cuerpoJLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cuerpoJLabel.setText("Enviando email...");

        tituloJlabel.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        tituloJlabel.setForeground(new java.awt.Color(51, 153, 255));
        tituloJlabel.setText("SISTEMA SUELDOS -  ENVIOS SICOSS ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(tituloJlabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(image)
                            .addComponent(cuerpoJLabel))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tituloJlabel)
                .addGap(18, 18, 18)
                .addComponent(image)
                .addGap(18, 18, 18)
                .addComponent(cuerpoJLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void cargarImagenes() {
//        String dirActual = System.getProperty("user.dir");
//        image.setIcon(new javax.swing.ImageIcon(dirActual + "\\images\\clock.png"));
//        this.setAlwaysOnTop(false);
       // Utils.setarIconVentana(this, dirActual);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel cuerpoJLabel;
    javax.swing.JLabel image;
    javax.swing.JLabel tituloJlabel;
    // End of variables declaration//GEN-END:variables
}
